Vagrant.configure("2") do |config|

	#config.vm.boot_timeout = 600
	config.vm.provider :virtualbox do |virtualbox|
		virtualbox.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
		virtualbox.gui = false
	end

	config.vm.define "dc1" do |dc1|
	  dc1.vm.box = "gusztavvargadr/w16s"
	  dc1.vm.network "private_network", ip: "192.168.60.2"
	  dc1.vm.provision "shell", inline: "C:/vagrant/ansible_setup.ps1 -ForceNewSSLCert"
	end

	config.vm.define "ansible_server" do |ansible|
		ansible.vm.box = "bento/centos-7.4"
		ansible.vm.network "private_network", ip: "192.168.60.3"
		ansible.vm.provision "shell", inline: "sudo service network restart"
		ansible.vm.provision "shell", inline: "sudo yum -y install epel-release && sudo yum -y install python-pip"
		ansible.vm.provision "shell", inline: "sudo pip install ansible pywinrm"
		ansible.vm.provision "shell", inline: "cd /vagrant/ && ansible-playbook domain_controller_dns.yml -i inventory"
	end
end
